{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO1qnt9jmulQ3GwtgsU9ht0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mishikamishra/Grocery-stock-tracker-/blob/main/GroceryStoreTracker.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "vLhDA4bEaQCN",
        "outputId": "457dafb7-c932-4f15-e64d-819cf3cae90d",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "GROCERY INVENTORY\n",
            "1 add item\n",
            "2 update stock\n",
            "3 show everything\n",
            "4 total value\n",
            "5 quit\n",
            "-------------------------------------------------------\n"
          ]
        }
      ],
      "source": [
        "\n",
        "inventory = {\n",
        "    \"Milk\": {\"price\": 3.50, \"quantity\": 50},\n",
        "    \"Bread\": {\"price\": 2.25, \"quantity\": 5},\n",
        "    \"Eggs\": {\"price\": 4.00, \"quantity\": 12},\n",
        "    \"Sugar\": {\"price\": 1.50, \"quantity\": 15}\n",
        "}\n",
        "\n",
        "low_threshold = 10\n",
        "sep = \"-\" * 55\n",
        "\n",
        "def add_item():\n",
        "    print(sep)\n",
        "    name = input(\"enter item name: \").strip().title()\n",
        "\n",
        "    if name in inventory:\n",
        "        print(name, \"already exists dude, use update instead\")\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        price = float(input(\"price: \"))\n",
        "        qty = int(input(\"how many: \"))\n",
        "    except:\n",
        "        print(\"bruh type numbers\")\n",
        "        return\n",
        "\n",
        "    if price < 0 or qty < 0:\n",
        "        print(\"negative?? nah\")\n",
        "        return\n",
        "\n",
        "    inventory[name] = {\"price\": price, \"quantity\": qty}\n",
        "    print(\"added\", qty, name, \"at\", price)\n",
        "\n",
        "def update_stock():\n",
        "    print(sep)\n",
        "    name = input(\"what item: \").strip().title()\n",
        "\n",
        "    if name not in inventory:\n",
        "        print(\"cant find\", name)\n",
        "        return\n",
        "\n",
        "    print(\"current:\", inventory[name][\"quantity\"])\n",
        "\n",
        "    try:\n",
        "        change = int(input(\"add or remove how many (can be negative): \"))\n",
        "    except:\n",
        "        print(\"not a number smh\")\n",
        "        return\n",
        "\n",
        "    new_qty = inventory[name][\"quantity\"] + change\n",
        "\n",
        "    if new_qty < 0:\n",
        "        print(\"not enough stock bro only got\", inventory[name][\"quantity\"])\n",
        "        return\n",
        "\n",
        "    inventory[name][\"quantity\"] = new_qty\n",
        "    print(\"ok now its\", new_qty)\n",
        "\n",
        "def show_inventory():\n",
        "    print(sep)\n",
        "    if not inventory:\n",
        "        print(\"empty lol\")\n",
        "        return\n",
        "\n",
        "    print(f\"{'ITEM':<15} {'PRICE':<10} {'QTY':<6} STATUS\")\n",
        "    print(sep)\n",
        "\n",
        "    low_count = 0\n",
        "    for item in sorted(inventory):\n",
        "        p = inventory[item][\"price\"]\n",
        "        q = inventory[item][\"quantity\"]\n",
        "\n",
        "        if q < low_threshold:\n",
        "            status = \"LOW\"\n",
        "            low_count += 1\n",
        "        else:\n",
        "            status = \"ok\"\n",
        "\n",
        "        print(f\"{item:<15} ${p:<9.2f} {q:<6} {status}\")\n",
        "\n",
        "    print(sep)\n",
        "    print(\"total items:\", len(inventory))\n",
        "    if low_count:\n",
        "        print(low_count, \"things running low btw\")\n",
        "\n",
        "def total_value():\n",
        "    total = 0\n",
        "    for stuff in inventory.values():\n",
        "        total += stuff[\"price\"] * stuff[\"quantity\"]\n",
        "\n",
        "    print(sep)\n",
        "    print(\"total value: $\", round(total, 2))\n",
        "    print(sep)\n",
        "\n",
        "def menu():\n",
        "    while True:\n",
        "        print(\"\\nGROCERY INVENTORY\")\n",
        "        print(\"1 add item\")\n",
        "        print(\"2 update stock\")\n",
        "        print(\"3 show everything\")\n",
        "        print(\"4 total value\")\n",
        "        print(\"5 quit\")\n",
        "        print(sep)\n",
        "\n",
        "        choice = input(\"pick 1-5: \").strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_item()\n",
        "        elif choice == \"2\":\n",
        "            update_stock()\n",
        "        elif choice == \"3\":\n",
        "            show_inventory()\n",
        "        elif choice == \"4\":\n",
        "            total_value()\n",
        "        elif choice == \"5\":\n",
        "            print(\"bye\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"invalid try again\")\n",
        "\n",
        "# run it\n",
        "menu()"
      ]
    }
  ]
}
